###############################################################################
#   @author       :   ArveVM
#   @date         :   21.march.2022
#   @integration  :   Recorder
#   @description  :   storine details in a database
#   @basic concept:
#     from https://github.com/frenck/home-assistant-config:
#       "The recorder component is storing details in a database which
#       then are handled by the history component."
#
#   further info: https://www.home-assistant.io/integrations/recorder
#
###############################################################################

recorder:
  commit_interval: 5
  #ArveVM; default was before 1 sec, changed ot new standard 5sec in march-25

  # The number of days of history to keep in the recorder database
  purge_keep_days: 9       # changed from 10 to 9 on 2023-12-11
  # ArveVM; default is 10 days

  #  auto_purge: false

  exclude:
    domains:
      #- automation
      - cover
      - light
      - updater
    entity_globs:
      - sensor.sun*
      - sensor.weather_*
    entities:
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.time_date
      - sensor.time
      - sensor.date
    event_types:
      - call_service # Don't record service calls

automation:
  - id: 3cfabc7f-de0f-42cc-8470-16b39c5aed71
    alias: Recorder purge noizy entities
    trigger:
      - platform: time
        at: "02:07:00"
    condition:
    actions:
      - action: recorder.purge_entities
        target:
          entity_id:
            - sensor.pwrctrl_ug_all_power      # +430' rows with 10days storage !!
            - sensor.pwrctrl_ug_ungrouped      # +290' rows with 10days storage !!
            - sensor.dream_machine_pro_cpu_utilization  # +415' rows with 10days storage !!
        #    - sensor.evahan_power
        #    - sensor.evahan_voltage
        #    - sensor.evahan_voltage_phase_b
        #    - sensor.evahan_voltage_phase_c
        #    - sensor.evahan_current
        #    - sensor.evahan_current_phase_b
        #    - sensor.evahan_current_phase_c
        #    - sensor.evahan_linkquality
        #    - sensor.evahan_temperature
        #    - sensor.evahan_org_energy2
        #    - sensor.evahan_last_seen
          entity_globs:
            - sensor.evahan_*
        data:
          domains: []
          entity_globs: []
          keep_days: 2
