# https://community.home-assistant.io/t/google-nest-hub-as-dashboard-with-dashcast-add-on/460217
# Mark that the auth_provider MUST be registered in configuration.yaml, and not included via packages :)
#   And the IP of hte nest-hub must be added under 'trusted_networks'

# CATT:
shell_command:
  hallway_nest_hub_cast1: !secret hallway_nest_hub_cast1    # show 'nest_hub_view.yaml'
  livingroom_chromecast1: "catt -d 'Livingroom chromecast' cast_site 'http://192.168.2.141:8121/nest-hub/nest_hub'"    # show 'nest_hub_view.yaml'


input_boolean:
  hallway_nest_hub_auto:
    name: Hallway Nest Hub auto
    icon: mdi:magic-staff

template:
  - binary_sensor:
      - name: Hallway Nest Hub DashCast on
        unique_id: 8ed760a2-3a19-471c-93a2-515f66e236232398
        state: >
          {{ is_state_attr('media_player.hallway_nest_hub', 'app_name', 'DashCast') }}

script:
  hallway_nest_hub:
    alias: Hallway Nest Hub
    sequence:
      # - conditions:
      #     - condition: template
      #       value_template: " {{ state_attr('media_player.hallway_nest_hub', 'app_name') != 'DashCast' }} "
      #     - condition: template
      #       value_template: " {{ state('input_boolean.hallway_nest_hub_recast') == 'on' }} "
          # - condition: state
          #   entity_id: input_boolean.hallway_nest_hub_recast
          #   state: "on"
      - service: media_player.volume_set
        data:
          volume_level: 0
        target:
          entity_id: media_player.hallway_nest_hub
      - service: shell_command.hallway_nest_hub_cast1


automation:
  - alias: "Hallway nest hub catt"
    description: "Hallway nest hub - cast with CATT"
    id: 2a778068-6620-4ae7-8a29-ed7097509333-s
    mode: single
    trigger:
      - id: focuschange
        platform: template
        value_template: " {{ state_attr('media_player.hallway_nest_hub', 'app_name') != 'DashCast' }} "
        for: "00:00:10"
      - id: recast
        platform: state
        entity_id: input_boolean.hallway_nest_hub_auto
        to: "on"
      - id: offf              # case for google updates etc etc,, give it five minutes and then recast :)
        platform: state
        entity_id: media_player.hallway_nest_hub
        to: "off"
        for: "00:05:00"
      - id: restart
        platform: homeassistant
        event: start
    condition: 
      - condition: state
        entity_id: input_boolean.hallway_nest_hub_auto
        state: "on"
    action:
      - choose:
          # after restart or device have been off,, await the catt uninstall/install procedure,,  before start casting
          - conditions:
              - condition: trigger
                id: 
                  - offf
                  - restart
            sequence:
              # Waits 1.5 minutes for catt-install to finish, or hub to restart
              - delay: "00:01:30"
              - service: script.hallway_nest_hub  # The script above

        # if not, start script -> casting
        default:
          - service: script.hallway_nest_hub  # The script above
            # data: {}
