# First add some customizations:
homeassistant:
  customize:
    package.node_anchors:
      # Add node-anchor for identification of code-location for created sensors
      solution_attribute_to_entity: &solution_attribute
        solution: "Kitchen"

    # Add node-anchor as attribute on created sensors (exept template-sensors - which is defined as attribute):
    light.kitchen_plug5_1_ball:
      <<: *solution_attribute
    light.kitchen_plug5_2_readinglight:
      <<: *solution_attribute
    sensor.kitchen_lights_all_power:
      <<: *solution_attribute
    sensor.kitchen_lights_all_energy:
      <<: *solution_attribute

# AVM: periphiral lights on a 5socket power-strip (https://www.zigbee2mqtt.io/devices/SM-0306E-2W.html#useelink-sm-0306e-2w)
#      change device class to light to enable control and power-monitoring as light
light:
  - platform: switch
    name: Kitchen plug5 ball
    entity_id: switch.kitchen_plug5_1_ball
  - platform: switch
    name: Kitchen plugl5 readinglight # AVM: will not add this to powercalc,, there is a manual switch which is used,, so I will only use this to turn off all light when leaving home/night
    entity_id: switch.kitchen_plug5_2_readinglight

  - platform: group
    name: Kitchen Lights group
    entities:
      - light.kitchen_light_pendant
      - light.kitchen_light_spot4
      - light.kitchen_light_windowstrip
      - light.kitchen_light_sink
      - light.kitchen_light_tablebulb

powercalc:
  sensors:
    - create_group: kitchen lights all # ArveVM; will create both power- and energy-sensors
      entities:
        - entity_id: light.kitchen_light_pendant   # ArveVM: Maron 5pc pendulum 2095-55 by Paul Neuhau
          fixed:
            power: 33
        - entity_id: light.kitchen_light_spot4  # AVM: 3*8w led 
          fixed:
            power: 18.0
        - entity_id: light.kitchen_light_windowstrip # AVM: Namron 89685 led-strip on a z2m-controller
          linear:
            min_power: 0.4
            max_power: 10.5
        - entity_id: light.kitchen_light_sink # AVM: Ikea TRÅDFRI 30w; powering Myrvarv strip (12W) and Vaxmyra spot (1.4 W)
          linear:
            min_power: 0.1
            max_power: 13.4
        - entity_id: light.kitchen_light_tablebulb # AVM: Ikea bulb on list of supported models https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md
          manufacturer: ikea
          model: LED1836G9
        - entity_id: light.kitchen_5plugl1_ball # AVM: conventional 25W E14 bulb
          linear:
            min_power: 0.0
            max_power: 25.0


template:
  - binary_sensor:
      - name: Kitchen Room Status
        unique_id: 2aaf1a19-8a0d-4046-ac3e-0bfd084bc0d0
        icon: mdi:check-circle
        device_class: problem
        # ArveVM; remember - a problem-check should be false, or else you have a problem :)
        state: >
          {{ states('input_boolean.dishwasher_emptying_todo') == 'off'
          and states('input_boolean.kitchen_heater_auto') != 'on'
          }}
        attributes:
          <<: *solution_attribute
          heater_powerauto: "{{ 'Problem!' if ( states('input_boolean.dishwasher_emptying_todo') == 'off' ) else 'OK'}}"
          dishwasher_emptying: "{{ 'Problem!' if ( states('input_boolean.kitchen_heater_auto') != 'on' ) else 'OK'}}"

automation:
  - alias: Kitchen Light 8switch
    id: ac8c5fab-90ff-4b47-8fe7-c8344328636a
    description: Control Namron K8 for kitchen linghts
    mode: single          
    trigger:
      # create triggerID's for different types of push/hold, and have corresponding actions in chooose-section
      # l= line,, so top line is l1 and bottom is l4
      # push is light push
      # release is the long-hold-release
      # hold is the brightnes_start - should be looped with a brightness_stop!
      - id: l1_left_push    # line1(top)-left push        
        platform: state
        entity_id:
          - sensor.kitchen_switch3_action
        to: on_l1
      - id: 1l_right_push     # line1-right push 
        platform: state
        entity_id:
          - sensor.kitchen_switch3_action
        to: off_l1
      - id: l4_right_release    # line4-right long-hold-release
        platform: state
        entity_id:
          - sensor.kitchen_switch3_action
        to: brightness_stop_l4
    condition: []
    action:
      - choose:
          # line1(top) left push  
          - conditions:
              - condition: trigger
                id: 1r_push
            sequence:
              - service: light.toggle
                data: {}
                target:
                  entity_id: light.kitchen_light_pendant
          
          # line1(top) right push
          - conditions:
              - condition: trigger
                id: 1l_right_push
            sequence:
              - service: light.toggle
                data: {}
                target:
                  entity_id: light.kitchen_light_spot4
    
          # line4-right long-hold-release
          - conditions:
              - condition: trigger
                id: l4_right_release
            sequence:
              - service: light.toggle
                data: {}
                target:
                  entity_id: light.laundry_lights_puck
