

homeassistant:
  customize:
    # # Add node-anchor as Attribute on used sensors from other integrations/solutions:
    light.kitchen_tealights:
      effect_list: candle, light

# # service: remote.learn_command
# service: remote.send_command
# target:
#   entity_id: remote.broadlink_kitchen
# data:
#   device: ledsavers_tealights2
#   # command_type: rf
#   command: 
#     # - turn on
#     # - light mode2
# #B64:JgB4AAABHZEREhE3ERQQExEUEBMRFBATETcRExE3ETcRNhE3ETcQOBAUERMQNxEUERIRFBATERQQOBA4EBMRNxE3EDgQOBA3EQAE6wABHkkRAAvqAAEdShEAC+kAAR5JEQAL6QABHkkRAAvpAAEeSREAC+kAAR1KEQANBQ==
#     # - turn on
#     # - B64:JgBoAAABHpEQExE3ERMRExETERMQFBETEDgQFBE2ETcQOBA4EDcRNxE3ERMQFBETEBQREhEUERIRFBA4EDgQNxA3ETcRNxE3EQAE6wABHkkRAAvpAAEeSREAC   # turn off

#     # Candle-mode:
#     - b64:JgB4AAABHZEREhE3ERQQExEUEBMRFBATETcRExE3ETcRNhE3ETcQOBAUERMQNxEUERIRFBATERQQOBA4EBMRNxE3EDgQOBA3EQAE6wABHkkRAAvqAAEdShEAC+kAAR5JEQAL6QABHkkRAAvpAAEeSREAC+kAAR1KEQANBQ==   # candle mode
       
#     # Light Mode:   
#     # - b64:JgCAAAABHZARFBA4EBMRFBATERMRFBESETcRExA4EDgQNxE3ETcRNxE3ERIRNxEUEBMRFBATERQQExE3ERMRNxE3ETcRNxA3EQAE7QABHUoRAAvqAAEeShAAC+sAAR5JEQAL6wABHkkQAAvqAAEfSREAC+kAAR5JEQAL6QABHkkQAA0F
  

light:
  - platform: template
    lights:
      kitchen_tealights:
        friendly_name: "Kitchen tealights"
        # level_template: "{{ state_attr('sensor.theater_brightness', 'lux')|int }}"
        # value_template: "{{ state_attr('sensor.theater_brightness', 'lux')|int > 0 }}"
        # temperature_template: "{{states('input_number.temperature_input') | int}}"
        # color_template: "({{states('input_number.h_input') | int}}, {{states('input_number.s_input') | int}})"
        # effect_list_template: "{{ state_attr('light.led_strip', 'effect_list') }}"
        # effect_list_template: "{{ state_attr('light.kitchen_tealights', 'effect_list') }}"
        #   - candle mode2
        #   - light mode2
        turn_on:
          service: remote.send_command
          target:
            entity_id: remote.broadlink_kitchen
          data:
            device: ledsavers_tealights2
            command: 
              - turn on
            # - light mode2
        #B64:JgB4AAABHZEREhE3ERQQExEUEBMRFBATETcRExE3ETcRNhE3ETcQOBAUERMQNxEUERIRFBATERQQOBA4EBMRNxE3EDgQOBA3EQAE6wABHkkRAAvqAAEdShEAC+kAAR5JEQAL6QABHkkRAAvpAAEeSREAC+kAAR1KEQANBQ==
            # - turn on
            # - B64:JgBoAAABHpEQExE3ERMRExETERMQFBETEDgQFBE2ETcQOBA4EDcRNxE3ERMQFBETEBQREhEUERIRFBA4EDgQNxA3ETcRNxE3EQAE6wABHkkRAAvpAAEeSREAC   # turn off

            # Candle-mode:
            # - b64:JgB4AAABHZEREhE3ERQQExEUEBMRFBATETcRExE3ETcRNhE3ETcQOBAUERMQNxEUERIRFBATERQQOBA4EBMRNxE3EDgQOBA3EQAE6wABHkkRAAvqAAEdShEAC+kAAR5JEQAL6QABHkkRAAvpAAEeSREAC+kAAR1KEQANBQ==   # candle mode
              
            # Light Mode:   
            # - b64:JgCAAAABHZARFBA4EBMRFBATERMRFBESETcRExA4EDgQNxE3ETcRNxE3ERIRNxEUEBMRFBATERQQExE3ERMRNxE3ETcRNxA3EQAE7QABHUoRAAvqAAEeShAAC+sAAR5JEQAL6wABHkkQAAvqAAEfSREAC+kAAR5JEQAL6QABHkkQAA0F

        turn_off:
          service: remote.send_command
          target:
            entity_id: remote.broadlink_kitchen
          data:
            device: ledsavers_tealights2
            command: 
              - turn off
        #set_effect:
        #  service: remote.send_command
        #  target:
        #    entity_id: remote.broadlink_kitchen
        #  data:
        #    device: ledsavers_tealights2
        #    command: "{{ effect }}"

        # mode_light:
        #   service: remote.send_command
        #   target:
        #     entity_id: remote.broadlink_kitchen
        #   data:
        #     device: ledsavers_tealights2
        #     command: 
        #       - light mode2