
homeassistant:
  customize:
    package.node_anchors:
      # Add node-anchor for identification of code-location for created sensors
      solution_attribute_to_entity: &solution_attribute
        solution: "Kitchen"
template:
  - binary_sensor:
      - name: Kitchen Room Status
        unique_id: 2aaf1a19-8a0d-4046-ac3e-0bfd084bc0d0
        icon: mdi:check-circle
        device_class: problem
        # ArveVM; remember - a problem-check should be false, or else you have a problem :)
        state: >
          {{ states('input_boolean.dishwasher_emptying_todo') == 'off'
          and states('input_boolean.kitchen_heater_auto') != 'on'
          }}
        attributes:
          <<: *solution_attribute
          heater_powerauto: "{{ 'Problem!' if ( states('input_boolean.dishwasher_emptying_todo') == 'off' ) else 'OK'}}"
          dishwasher_emptying: "{{ 'Problem!' if ( states('input_boolean.kitchen_heater_auto') != 'on' ) else 'OK'}}"

  - sensor:
    # https://www.reddit.com/r/homeassistant/comments/pqhk78/better_use_absolute_humidity_instead_of_relative/  
    - name: "Kitchen Absolute Humidity"
      unit_of_measurement: 'g/m^3'
      device_class: humidity
      state: >
        {% set cur_temp = states('sensor.kitchen_thp_temperature') | float %}
        {% set cur_humidity = states('sensor.kitchen_thp_humidity') | float %}
        {{ ((e ** ((17.67 * cur_temp) / (243.5 + cur_temp )) * 6.112 * cur_humidity * 2.1674 ) / (273.15 + cur_temp)) | round(1) }}
      # Area - manually added in GUI to area; bedroom


