


# First add some customizations:
homeassistant:
  customize:
    package.node_anchors:
      # Add node-anchor for identification of code-location for created sensors
      package_attribute_to_entity: &package_attribute
        package: 'Kitchen Heater'
      # Add node-anchor(s) for input-sensors to use as variables   - (theese are sensors from other integrations/solutions)
      power: &power sensor.kitchen_heater_power
      energy: &energy sensor.kitchen_heater_energy
      
    # Add node-anchor as attribute on created sensors:
    input_boolean.kitchen_heater_thermostat_output:
      <<: *package_attribute
    input_boolean.kitchen_heater_auto:
      <<: *package_attribute
    climate.kitchen_heater_thermostat:  
      <<: *package_attribute
    automation.kitchen_heater_auto_off:
      <<: *package_attribute
    automation.kitchen_heater_auto_on:
      <<: *package_attribute

template:
  - sensor:
      - name: "kitchen_heater_south_running"
        unique_id: "kitchen_heater_south_running"
        state: "{{ states('sensor.kitchen_heater_south_power') | float(0) > 7 }}"


input_boolean:
  kitchen_heater_thermostat_output:
    name: Kitchen Heater Thermostat Output
    icon: mdi:radiator
  kitchen_heater_auto:
    name: Kitchen Heater Auto
    icon: mdi:magic-staff

climate:
  - platform: generic_thermostat
    name: Kitchen Heater Thermostat
    unique_id: kitchen_heater_thermostat
    heater: input_boolean.kitchen_heater_thermostat_output
    target_sensor: sensor.kitchen_thp_temperature
    initial_hvac_mode: heat
    max_temp: 30
    # target_temp: 15                # AVM; ignored, willl restart at last value
    min_cycle_duration: "00:05"     # AVM; try limit switcing to 5min-periods (avoid on/of on local heatspot)
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    away_temp: 10             # for Home mode: vacation
    comfort_temp: 21          # for Home status: Evening, evening-grownups, kidrooms cold
    home_temp: 21             # for Home status: Daytime, 
    sleep_temp: 17            # for Home status: Night
    activity_temp: 21         # for Home status: Morning, exept office and bedrooms


automation:
  - id: 'kitchen_heater_auto_off'
    alias: "_Kitchen Heater; auto OFF"
    description: 'when auto is off; switch shold allways be on; using local thermostat on heater'
    mode: single
    trigger:
    - id: 'auto_off'
      platform: state
      entity_id: input_boolean.kitchen_heater_auto
      to: 'off'
    - platform: homeassistant
      event: start
    condition:
    - condition: state
      entity_id: input_boolean.kitchen_heater_auto
      state: 'off'
    action:
    - service: switch.turn_on
      target:
        entity_id: switch.kitchen_heater

  - id: 'kitchen_heater_auto_on'
    alias: "_Kitchen Heater; auto ON"
    description: 'when auto is on; switch shold following output from generic thermostat'
    mode: single
    trigger:
    - id: 'auto_on'
      platform: state
      entity_id: input_boolean.kitchen_heater_auto
      to: 'on'
    - id: 'thermostat_change'
      platform: state
      entity_id: input_boolean.kitchen_heater_thermostat_output
    condition:
    - condition: state
      entity_id: input_boolean.kitchen_heater_auto
      state: 'on'
    action:
    - service: "switch.turn_{{ 'on' if is_state('input_boolean.kitchen_heater_thermostat_output', 'on') else 'off' }}"
    #- service: "switch.turn_off"    #"switch.turn_{{ 'on' if is_state('input_boolean.kitchen_heater_thermostat_output', 'on') else 'off' }}"
      target: 
        entity_id: switch.kitchen_heater