


# template:
#   - sensor:
#       # get hold of han-port reading, round to use for display (and use to create utility-meters)
#       - name: PwrCtrl Use Total power
#         unique_id: 6b908ec4-eb24-4ea3-9dfe-320fc0d9632e
#         unit_of_measurement: W
#         device_class: power
#         # attributes:
#         #   <<: *solution_attribute
#         state: >
#           {% set w = states('sensor.evahan_power') | float %}
#           {{ w | round(0) }}

sensor:
  # eksempel fra Erlend Sellie på HA-norge-FB - brukt i en av lovelace-cards for nordpool vs current usage-grafs,,,
  - platform: filter
    unique_id: 9cba3cf7-eaf3-4ce0-a63d-af799cd49e69
    name: PwrCtrl Use Total filtered power
    entity_id: sensor.evahan_power
    filters:
      - filter: throttle
        window_size: 4
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10



powercalc:
  sensors:
    - create_group: PwrCtrl Use Total
      ignore_unavailable_state: true
      create_energy_sensor: true
      create_utility_meters: true
      entities:
        - power_sensor_id: sensor.evahan_power