# First add some customizations:
homeassistant:
  customize:
    package.node_anchors:
      # Add node-anchor for identification of code-location for created sensors
      solution_attribute_to_entity: &solution_attribute
        solution: "Kitchen"

    # Add node-anchor as attribute on created sensors (exept template-sensors - which is defined as attribute):
    light.kitchen_plug5_1_ball:
      <<: *solution_attribute
    light.kitchen_plug5_2_readinglight:
      <<: *solution_attribute
    sensor.kitchen_lights_all_power:
      <<: *solution_attribute
    sensor.kitchen_lights_all_energy:
      <<: *solution_attribute

# AVM: periphiral lights on a 5socket power-strip (https://www.zigbee2mqtt.io/devices/SM-0306E-2W.html#useelink-sm-0306e-2w)
#      change device class to light to enable control and power-monitoring as light
light:
  - platform: switch
    name: Kitchen plug5 ball
    entity_id: switch.kitchen_plug5_1_ball
  - platform: switch
    name: Kitchen plugl5 readinglight # AVM: will not add this to powercalc,, there is a manual switch which is used,, so I will only use this to turn off all light when leaving home/night
    entity_id: switch.kitchen_plug5_2_readinglight

  - platform: group
    name: Kitchen Lights group
    entities:
      - light.kitchen_switch1 
      - light.kitchen_light_windowstrip
      - light.kitchen_light_sink
      - light.kitchen_light_tablebulb

sensor:
  - platform: powercalc
    create_group: kitchen lights all # ArveVM; will create both power- and energy-sensors
    #    create_energy_sensor: true
    entities:
      - entity_id: light.kitchen_switch1  # AVM: 3*8w led 
        linear:
          min_power: 0.0
          max_power: 18.0
      - entity_id: light.kitchen_light_windowstrip # AVM: Namron 89685 led-strip on a z2m-controller
        linear:
          min_power: 0.4
          max_power: 10.5
      - entity_id: light.kitchen_light_sink # AVM: Ikea TRÅDFRI 30w; powering Myrvarv strip (12W) and Vaxmyra spot (1.4 W)
        linear:
          min_power: 0.1
          max_power: 13.4
      - entity_id: light.kitchen_light_tablebulb # AVM: Ikea bulb on list of supported models https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md
        manufacturer: ikea
        model: LED1836G9
      - entity_id: light.kitchen_5plugl1_ball # AVM: conventional 25W E14 bulb
        linear:
          min_power: 0.0
          max_power: 25.0

template:
  - binary_sensor:
      - name: Kitchen Room Status
        unique_id: 2aaf1a19-8a0d-4046-ac3e-0bfd084bc0d0
        icon: mdi:check-circle
        device_class: problem
        # ArveVM; remember - a problem-check should be false, or else you have a problem :)
        state: >
          {{ states('input_boolean.dishwasher_emptying_todo') == 'off'
          and states('input_boolean.kitchen_heater_auto') != 'on'
          }}
        attributes:
          <<: *solution_attribute
          heater_powerauto: "{{ 'Problem!' if ( states('input_boolean.dishwasher_emptying_todo') == 'off' ) else 'OK'}}"
          dishwasher_emptying: "{{ 'Problem!' if ( states('input_boolean.kitchen_heater_auto') != 'on' ) else 'OK'}}"
