# https://github.com/ArveVM/MyAssistedHome/wiki/Solution-Adguard

input_datetime:
  adguard_home_filter_off_timer:
    name: Adguard Home filter off timer
    has_date: false
    has_time: true
    initial: 00:30

timer:
  adguard_home_filter_off:
    duration: 00:30

script:
  adguard_home_filter_off:
    sequence:
      - service: timer.start
        data:
          duration: >
            {{states('input_datetime.adguard_home_filter_off_timer')}}
        target:
          entity_id: timer.adguard_home_filter_off
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.adguard_home_filtering

automation:
  - alias: "_Adguard Home timer; stop"
    id: 2a778068-6620-4ae7-8a29-ed7097509333
    trigger:
      - id: pause
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.adguard_home_filter_off       
    action:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.adguard_home_filtering
